/*********************************************************************
*                SEGGER MICROCONTROLLER SYSTEME GmbH                 *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*
* C-file generated by
*
*        µC/GUI-BitmapConvert V3.90.
*        Compiled Aug 19 2004, 09:07:56
*          (c) 2002  Micrium, Inc.
  www.micrium.com

  (c) 1998-2002  Segger
  Microcontroller Systeme GmbH
  www.segger.com
*
**********************************************************************
*
* Source file: feegnshi1
* Dimensions:  48 * 32
* NumColors:   2
*
**********************************************************************
*/

#include "stdlib.h"
#include "feegnshi1.h"


#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/*   Palette
The following are the entries of the palette table.
Every entry is a 32-bit value (of which 24 bits are actually used)
the lower   8 bits represent the Red component,
the middle  8 bits represent the Green component,
the highest 8 bits (of the 24 bits used) represent the Blue component
as follows:   0xBBGGRR
*/

static GUI_CONST_STORAGE GUI_COLOR Colorsfeegnshi1[] = {
     0x000000,0xFFFFFF
};

static GUI_CONST_STORAGE GUI_LOGPALETTE Palfeegnshi1 = {
  2,	/* number of entries */
  0, 	/* No transparency */
  &Colorsfeegnshi1[0]
};

static GUI_CONST_STORAGE unsigned char acfeegnshi1[] = {
  ________, ________, ________, ________, XXXXXXXX, XXXXXXXX,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, XXX_____, _____XXX,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, XXX_XXXX, XXXX_XXX,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, XXX_XXXX, XXXX_XXX,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, XXX_X_XX, XX_X_XXX,
  _XXXXXXX, XXXX_X__, ___X_XXX, XXXXXXX_, XXX_XX_X, XX_X_XXX,
  _XXXXXXX, XXXX_X__, ___X_XXX, XXXXXXX_, XXX_XXX_, X_XX_XXX,
  _XXXXXXX, XXXX_X__, ___X_XXX, XXXXXXX_, XXX_XXX_, X_XX_XXX,
  _XXXXXXX, XXX__X__, ___X__XX, XXXXXXX_, XXX_XXXX, _XXX_XXX,
  _XXXXXXX, XX__XX__, ___XX___, XXXXXXX_, XXX_XXXX, _XXX_XXX,
  _XXXXXXX, X__XX___, ____XXX_, _XXXXXX_, XXX_XXX_, X_XX_XXX,
  _XXXXXXX, __XX____, _____XXX, X_XXXXX_, XXX_XXX_, X_XX_XX_,
  _XXXXXX_, _XX_____, ______XX, X_XXXXX_, XXX_XX_X, XX_XX_X_,
  _XXXXXX_, XXX_____, ______XX, X_XXXXX_, XX_XX_XX, XX_XX_X_,
  _XXXXXX_, XXXXX___, ___XXXXX, X_XXXXX_, XX_XXXXX, XXXXXX__,
  _XXXXXX_, XX__XXX_, _XXX__XX, __XXXXX_, X_XXXXXX, XXXXXXX_,
  _XXXXXXX, _XX___XX, XX___XX_, _XXXXXX_, XXXXXXXX, XXXXXXXX,
  _XXXXXXX, X_XXX___, ____X__X, XXXXXXX_, XXX_XX__, ______XX,
  _XXXXXXX, XX__X___, ___X__XX, XXXXXXX_, XXXX_X_X, XXXXX_XX,
  _XXXXXXX, XXX__X__, ___X_XXX, XXXXXXX_, XXXX_X_X, XXXXX_XX,
  _XXXXXXX, XXXX_X__, ___X_XXX, XXXXXXX_, X_XXXX__, ______XX,
  _XXXXXXX, XXXX_X__, ___X_XXX, XXXXXXX_, XX_XXX_X, XXXXX_XX,
  _XXXXXXX, XXXX_X__, ___X_XXX, XXXXXXX_, XX_XXX_X, XXXXX_XX,
  _XXXXXXX, XXXX_X__, ___X_XXX, XXXXXXX_, XXXX_X__, ______XX,
  _XXXXXXX, XXXX_X__, ___X_XXX, XXXXXXX_, XXXX_XXX, _XX_XXXX,
  _XXXXXXX, XXXX_X__, ___X_XXX, XXXXXXX_, XXX_XXXX, _XX_XXXX,
  _XXXXXXX, XXXX_X__, ___X_XXX, XXXXXXX_, X___X_XX, _XX_XX_X,
  _XXXXXXX, XXXX_X__, ___X_XXX, XXXXXXX_, XXX_XX_X, _XX_X_XX,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, XXX_XXX_, _XX__XXX,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, XXX_XXXX, _XX_XXXX,
  _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, XXX_X___, ________,
  ________, ________, ________, ________, XXXXXXXX, XXXXXXXX
};

GUI_CONST_STORAGE GUI_BITMAP bmfeegnshi1 = {
  48, /* XSize */
  32, /* YSize */
  6, /* BytesPerLine */
  1, /* BitsPerPixel */
  acfeegnshi1,  /* Pointer to picture data (indices) */
  &Palfeegnshi1  /* Pointer to palette */
};

/* *** End of file *** */
